Feat/header
SynergyWire/SynergyWire-Blog pull request #1
Opened 2023-07-18 21:14 UTC by Sierra9999

2023-07-19 21:40 UTC, calixfar requested changes

2023-07-19 21:40 UTC, calixfar commented on components/Header/header.css
> +.responsive-menu {
Please indent the whole content to 2 spaces.

2023-07-19 21:40 UTC, calixfar commented on app/layout.tsx
> -  description: 'dedicated blog to talk about topics related to: tecnology, software development, frontend, backend, clean code, data structure, design patterns and also other topics more close to the
Why did you remove keywords on the description? This is content is aimed to better seo

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +
Remove empty line

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +
Remove empty line

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +
Remove empty line

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +
Remove empty line

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +
Remove empty line

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +          <svg className="menu-icon-burger"
Could you create a component Icon to these svg. Follow the example on the components folder.

2023-07-19 21:40 UTC, calixfar commented on components/Header/index.tsx
> +  );
Remove ;

2023-07-19 21:40 UTC, calixfar commented on components/Header/header.css
> +
Remove empty line. There must just be one empty line between blocks.

2023-07-20 22:12 UTC, Sierra9999 commented on app/layout.tsx
> -  description: 'dedicated blog to talk about topics related to: tecnology, software development, frontend, backend, clean code, data structure, design patterns and also other topics more close to the
The content will be discussed and created in the next meeting, in order to get a clearer concept of what synergy wire will be

2023-07-21 20:30 UTC, calixfar commented on utils/types.ts
> +export type IconKey = 'GITHUB' | 'LINKEDIN' | 'TWITTER' |'MENU'|'CLOSE'
```suggestion
export type IconKey = 'GITHUB' | 'LINKEDIN' | 'TWITTER' | 'MENU' | 'CLOSE'
```
Add blank spaces between options

2023-07-21 20:31 UTC, calixfar commented on components/icons/Icon.tsx
> +    CLOSE: IconX
Is it not better if you named the icon as IconClose?

2023-07-21 20:34 UTC, calixfar commented on components/Header/index.tsx
> +import React from "react";
Please keep a format, you are calling the imports with double quotes but on other files it is just single quote. I would rather have one quote and no ;

2023-07-28 00:31 UTC, calixfar approved these changes

2023-07-28 17:14 UTC, merged